# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: InstallAppleCertificatem@2
  inputs:
    certSecureFile: 'ia.p12'
    keychain: 'temp'
    certPwd: test

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'TestProfile.mobileprovision'

- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    packageApp: false
    signingOption: 'manual'
    signingIdentity: 'Egr2'
    provisioningProfileUuid: 'e75cf333-41c0-4174-be83-2c140c308366'
    provisioningProfileName: 'TestProfile'





    
